// イカ食堂の「山口で釣れるイカ」別の中身（2026-09-28 ぱっぱ：アオリ・コウイカ・モンゴウ・ヤリ・ケンサキのレシピとバリエーション、生食も載せる）。
// ブラウザのAPIに触らない（ビルド時の事前描画でも読むため）。data.js の recipes の後ろにつながる。
// 分量は2人分（recipe-scale.js で4人分に換算）。生で食べる品（raw: true）は、厚生労働省の案内どおり
// 「−20℃以下で24時間以上の冷凍」を手順に必ず入れる。酢・塩・醤油・わさびではアニサキスは防げない
const pair = (ja, en) => ({ ja, en });

// 山口で釣れる5種（id は図鑑 species の id と同じ）。best は向く料理のレシピ id
export const kitchenSquid = [
  {
    id: 'aori',
    name: pair('アオリイカ', 'Bigfin reef squid'),
    season: pair('春（大きな親イカ）・秋（新子）', 'Spring (large adults) and autumn (young of the year)'),
    body: pair('身が厚くやわらかく、甘みが強い「イカの王様」。刺身でも火を通しても。', 'Thick, tender and sweet: the “king of squid.” Excellent raw or cooked.'),
    best: ['aori-sashimi', 'aori-tempura', 'butter'],
  },
  {
    id: 'kensaki',
    name: pair('ケンサキイカ', 'Swordtip squid'),
    season: pair('初夏〜秋（須佐の「須佐男命いか」）', 'Early summer to autumn (Susa’s “Susa Mikoto Ika”)'),
    body: pair('甘みが濃く、やわらかい。丸ごと焼いても、詰め物をしても。', 'Rich, sweet and tender. Great grilled whole or stuffed.'),
    best: ['kensaki-shioyaki', 'ikameshi', 'aori-sashimi'],
  },
  {
    id: 'yari',
    name: pair('ヤリイカ', 'Spear squid'),
    season: pair('冬〜春（春は子持ち）', 'Winter to spring (females carry eggs in spring)'),
    body: pair('身が薄くやわらかく、上品な味。さっと煮るのがいちばん。', 'Thin, tender and delicate. Best simmered briefly.'),
    best: ['yari-nitsuke', 'yari-okizuke', 'daikon'],
  },
  {
    id: 'kouika',
    name: pair('コウイカ', 'Golden cuttlefish'),
    season: pair('春', 'Spring'),
    body: pair('身が厚く、ねっとりした甘み。背中に甲があり、墨がたっぷり。', 'Thick flesh with a mellow sweetness. Has an internal shell and plenty of ink.'),
    best: ['kou-sumi-pasta', 'kou-fry', 'pasta'],
  },
  {
    id: 'mongo',
    name: pair('モンゴウイカ', 'Kisslip cuttlefish'),
    season: pair('初夏', 'Early summer'),
    body: pair('大きく身が厚い。しっかりした歯ごたえで、揚げ物・炒め物向き。', 'Large and thick with a firm bite—made for frying and stir-fries.'),
    best: ['mongo-karaage', 'mongo-stirfry', 'kou-fry'],
  },
];

// 釣ったイカの下処理（一覧ページの下に出す）
export const kitchenPrep = [
  {
    title: pair('釣れたら、すぐ締める', 'Dispatch it right away'),
    steps: [
      pair('目と目の間（胴と頭のつけ根）を、イカ締めピックやナイフの先で刺す。体の色がすっと白く変われば締まった合図。', 'Pierce between the eyes, where the mantle meets the head, with a squid pick or knife tip. The body turns pale when done.'),
      pair('墨を吐くので、海に向けて、服にかからない向きで。', 'Point it toward the sea—squid squirt ink.'),
    ],
  },
  {
    title: pair('冷やして持ち帰る', 'Keep it cold on the way home'),
    steps: [
      pair('1杯ずつ袋に入れる（墨でほかのイカが汚れない）。', 'Bag each squid separately so ink does not stain the rest.'),
      pair('氷や保冷剤に直接当てず、新聞紙やタオル越しにクーラーで冷やす（身の色が悪くなりにくい）。', 'Chill in a cooler with newspaper or a towel between the squid and the ice to keep the flesh looking good.'),
    ],
  },
  {
    title: pair('さばく：アオリ・ケンサキ・ヤリ', 'Cleaning: bigfin, swordtip and spear squid'),
    steps: [
      pair('胴と足のつけ根に指を入れ、はがしてから、足をワタごとゆっくり引き抜く。墨袋を破らないように。', 'Slide a finger between mantle and arms, loosen, then gently pull the arms and innards out together without bursting the ink sac.'),
      pair('胴の中の透明な軟骨を抜き、水で洗う。エンペラ（ひれ）をはがし、そこから薄皮をむく。', 'Pull out the clear cartilage and rinse. Peel off the fins, then peel away the skin from there.'),
      pair('足は目の下で切り、目とクチバシを取る。吸盤の硬い輪は、包丁でしごいて落とす。', 'Cut the arms just below the eyes, remove eyes and beak, and scrape off the hard sucker rings.'),
    ],
  },
  {
    title: pair('さばく：コウイカ・モンゴウイカ', 'Cleaning: cuttlefish'),
    steps: [
      pair('墨が飛ぶので、シンクの中で。まな板にラップを敷き、エプロンを。', 'Work in the sink—ink splashes. Cover the board with plastic wrap and wear an apron.'),
      pair('背中の中央に包丁を入れ、白い甲を押し出して外す。', 'Cut down the center of the back and push out the white cuttlebone.'),
      pair('ワタについている墨袋をつまんで外す（墨料理に使える）。ワタと足を外し、皮をむく。', 'Pinch off the ink sac (save it for ink dishes), remove innards and arms, then peel the skin.'),
    ],
  },
  {
    title: pair('生で食べるときの約束', 'Before eating it raw'),
    raw: true,
    steps: [
      pair('イカにはアニサキス（寄生虫）がいることがあります。生で食べるなら、下処理した身を−20℃以下で24時間以上冷凍してから（厚生労働省の案内）。冷凍庫の温度表示が−20℃以下になっているか確かめる。', 'Squid can carry Anisakis parasites. To eat it raw, freeze the cleaned flesh at −20°C or below for at least 24 hours (Japan’s Ministry of Health guidance). Check that your freezer actually reaches −20°C.'),
      pair('食べる前に冷蔵庫で解凍し、身の表面に白い糸のような虫がいないか目で見て確かめる。', 'Thaw in the refrigerator and look over the surface for thin white threads before serving.'),
      pair('酢・塩・醤油・わさびでは防げません。加熱するなら中心まで（70℃以上、または60℃なら1分）。', 'Vinegar, salt, soy sauce and wasabi do not prevent it. When cooking, heat through to the center (70°C, or 60°C for one minute).'),
    ],
  },
  {
    title: pair('冷凍して保存する', 'Freezing for later'),
    steps: [
      pair('さばいて水分をよくふき、1回分ずつラップで包んで保存袋へ。空気を抜いて平らにする。', 'Clean, pat dry, wrap in single portions and seal flat in freezer bags with the air pressed out.'),
      pair('使うときは冷蔵庫でゆっくり解凍する。', 'Thaw slowly in the refrigerator.'),
    ],
  },
];

// 追加のレシピ10品（2人分）
export const moreRecipes = [
  {
    id: 'aori-sashimi',
    name: pair('アオリイカの刺身（冷凍してから）', 'Bigfin squid sashimi (frozen first)'),
    time: 20,
    kind: pair('生で', 'Raw'),
    icon: '🍣',
    raw: true,
    squid: ['aori', 'kensaki', 'yari'],
    intro: pair('ねっとり甘いアオリイカを、いちばん素直に。冷凍の約束を守って、安心して。', 'The simplest way to enjoy sweet bigfin squid—safely, by freezing it first.'),
    ingredients: [
      [pair('さばいたアオリイカの胴（薄皮をむいたもの）', 'Cleaned, skinned bigfin squid mantle'), 200, 'g'],
      [pair('大葉', 'Shiso leaves'), 4, pair('枚', '')],
      [pair('おろし生姜', 'Grated ginger'), 5, 'g'],
      [pair('醤油', 'Soy sauce'), 15, 'ml'],
    ],
    steps: [
      pair('胴の水分をよくふき、ラップで包んで保存袋へ。−20℃以下で24時間以上冷凍する。', 'Pat the mantle dry, wrap it and seal in a freezer bag. Freeze at −20°C or below for at least 24 hours.'),
      pair('食べる半日〜1日前に冷蔵庫へ移して解凍する（少し凍っているほうが切りやすい）。', 'Move it to the refrigerator half a day to a day before serving (slightly frozen is easier to slice).'),
      pair('身の表面に白い糸のような虫がいないか、目で見て確かめる。', 'Check the surface for thin white threads.'),
      pair('5mmほどの厚さにそぎ切りにし、大葉を敷いた器に盛る。生姜醤油で。', 'Slice about 5mm thick on the diagonal and serve on shiso with ginger soy sauce.'),
    ],
    tip: pair('一度冷凍すると身がやわらかくなり、甘みを感じやすいとも言われます。釣った日の「当日刺身」は勧めません。', 'Freezing also softens the flesh and is said to bring out its sweetness. We do not recommend same-day sashimi.'),
    variations: [
      [pair('イカそうめん', 'Squid “noodles”'), pair('細く切り、めんつゆとうずらの卵黄で。', 'Cut into thin strips and serve with noodle dipping sauce and a quail egg yolk.')],
      [pair('塩レモンのカルパッチョ', 'Salt-and-lemon carpaccio'), pair('薄切りを並べ、塩・レモン汁・オリーブ油をかける。', 'Lay thin slices flat and dress with salt, lemon juice and olive oil.')],
      [pair('ゲソは焼いて', 'Grill the arms'), pair('足は刺身にせず、バター醤油で焼いてもう一品に。', 'Rather than eating the arms raw, sauté them in soy butter for a second dish.')],
    ],
  },
  {
    id: 'aori-tempura',
    name: pair('アオリイカの天ぷら', 'Bigfin squid tempura'),
    time: 20,
    kind: pair('揚げる', 'Deep-fry'),
    icon: '🍤',
    squid: ['aori', 'kensaki', 'mongo'],
    intro: pair('厚い身がふわっと甘い。胴もゲソも、揚げたてを塩で。', 'Thick, sweet squid turns soft and tender. Eat it hot with salt.'),
    ingredients: [
      [pair('さばいたイカ（胴・ゲソ）', 'Cleaned squid (mantle and arms)'), 250, 'g'],
      [pair('天ぷら粉', 'Tempura flour'), 60, 'g'],
      [pair('冷水', 'Ice-cold water'), 90, 'ml'],
      [pair('揚げ油', 'Oil for frying'), 500, 'ml'],
      [pair('塩', 'Salt'), 2, 'g'],
    ],
    steps: [
      pair('胴は薄皮をむいて1cm幅に、ゲソは2本ずつに切る。キッチンペーパーで水分をしっかりふく。', 'Skin the mantle and cut into 1cm strips; cut the arms in pairs. Pat everything very dry.'),
      pair('天ぷら粉と冷水をさっくり混ぜる（混ぜすぎない）。', 'Stir tempura flour and cold water together lightly—do not overmix.'),
      pair('170℃の油で、衣がカリッとして中まで火が通るまで1〜2分揚げる。', 'Fry at 170°C for 1–2 minutes until crisp and cooked through.'),
      pair('油をきって、塩を添える。', 'Drain and serve with salt.'),
    ],
    tip: pair('イカは水分が多く、油がはねやすい。薄皮をむく・水分をふく・浅い切り目を入れる、の3つで防げます。', 'Squid is watery and spits in hot oil. Skinning, drying and scoring it lightly all help.'),
    variations: [
      [pair('カレー塩', 'Curry salt'), pair('塩にカレー粉を少し混ぜて。', 'Mix a little curry powder into the salt.')],
      [pair('磯辺揚げ', 'Nori-flecked tempura'), pair('衣に青のりを混ぜる。', 'Stir green laver flakes into the batter.')],
      [pair('ゲソのかき揚げ', 'Tentacle fritters'), pair('刻んだゲソと玉ねぎを衣でまとめて揚げる。', 'Fry chopped arms and onion bound with batter.')],
    ],
  },
  {
    id: 'kensaki-shioyaki',
    name: pair('ケンサキイカの丸ごと塩焼き', 'Whole grilled swordtip squid with salt'),
    time: 15,
    kind: pair('焼く', 'Grill'),
    icon: '🔥',
    squid: ['kensaki', 'yari', 'aori'],
    intro: pair('甘いケンサキイカを、塩だけで。焼きたてを輪切りに。', 'Sweet swordtip squid needs nothing but salt. Slice it into rings straight off the grill.'),
    ingredients: [
      [pair('ケンサキイカ（中）', 'Swordtip squid, medium'), 2, pair('杯', '')],
      [pair('酒', 'Sake'), 15, 'ml'],
      [pair('塩', 'Salt'), 3, 'g'],
      [pair('レモン（くし切り）', 'Lemon wedges'), 2, pair('切れ', '')],
    ],
    steps: [
      pair('足とワタ、軟骨を抜き、胴は開かずに洗って水分をふく。胴に斜めの浅い切り目を数本入れる（反り返りを防ぐ）。', 'Remove arms, innards and cartilage; rinse the tube whole and pat dry. Score the mantle lightly on the diagonal to stop it curling.'),
      pair('胴と足に酒と塩をまぶして5分置く。', 'Coat mantle and arms with sake and salt and rest 5 minutes.'),
      pair('魚焼きグリルかフライパンの中火で、両面に焼き色がつき、厚い所まで熱くなるまで焼く（片面3〜4分が目安）。', 'Grill or pan-fry over medium heat until browned on both sides and hot through the thickest part (about 3–4 minutes a side).'),
      pair('輪切りにして、レモンを添える。', 'Slice into rings and serve with lemon.'),
    ],
    tip: pair('身が白く不透明になり、中まで熱くなったら焼き上がり。それ以上焼くと硬くなります。', 'It is done when opaque and hot all the way through; beyond that it toughens.'),
    variations: [
      [pair('醤油みりん焼き', 'Soy-mirin glaze'), pair('焼き上がり直前に醤油とみりんを1:1で塗って、香ばしく。', 'Brush with equal parts soy and mirin just before it is done.')],
      [pair('ワタ焼き', 'Grilled with its own liver'), pair('新鮮なワタを醤油と混ぜて胴に塗り、中までしっかり焼く。', 'Mix the fresh liver with soy sauce, brush it on and cook through completely.')],
      [pair('ゲソのバター焼き', 'Buttered arms'), pair('足はバターで炒めて、もう一品。', 'Sauté the arms in butter for a second small plate.')],
    ],
  },
  {
    id: 'ikameshi',
    name: pair('イカ飯', 'Rice-stuffed squid (ikameshi)'),
    time: 60,
    kind: pair('煮る', 'Simmer'),
    icon: '🍙',
    squid: ['kensaki', 'yari'],
    intro: pair('もち米を詰めて甘辛く煮る、ごちそう。小ぶりのケンサキやヤリイカで。', 'Squid stuffed with sticky rice and simmered sweet and savory. Small swordtip or spear squid work best.'),
    ingredients: [
      [pair('小〜中のイカ', 'Small to medium squid'), 4, pair('杯', '')],
      [pair('もち米', 'Glutinous rice'), 90, 'g'],
      [pair('水', 'Water'), 300, 'ml'],
      [pair('醤油', 'Soy sauce'), 30, 'ml'],
      [pair('みりん', 'Mirin'), 30, 'ml'],
      [pair('砂糖', 'Sugar'), 15, 'g'],
      [pair('生姜（薄切り）', 'Sliced ginger'), 5, 'g'],
    ],
    steps: [
      pair('もち米を洗って1時間水につけ、ざるに上げる。', 'Rinse the rice, soak for 1 hour and drain.'),
      pair('イカの足・ワタ・軟骨を抜き、胴をよく洗って水分をふく。足は刻んでもち米に混ぜる。', 'Remove arms, innards and cartilage; rinse the tubes and pat dry. Chop the arms and mix into the rice.'),
      pair('胴の6〜7分目までもち米を詰め、口をつまようじで留める（米がふくらむので詰めすぎない）。', 'Fill each tube only two-thirds full—the rice swells—and close with a toothpick.'),
      pair('鍋に水・調味料・生姜を煮立て、イカを入れて落としぶたをする。弱めの中火で約40分、途中で返しながら、もち米がやわらかくなるまで煮る。', 'Bring the water, seasonings and ginger to a boil, add the squid and cover with a drop lid. Simmer about 40 minutes over medium-low heat, turning occasionally, until the rice is soft.'),
      pair('少し冷ましてから輪切りにする。', 'Let it cool a little before slicing.'),
    ],
    tip: pair('詰めすぎると煮ている間に破れます。煮汁が少なくなったら水を足して。', 'Overfilled squid burst as they cook. Add water if the liquid runs low.'),
    variations: [
      [pair('うるち米を混ぜて', 'Half regular rice'), pair('もち米の半分をふつうの米にすると、軽い食感に。', 'Replace half the glutinous rice with regular rice for a lighter texture.')],
      [pair('炊き込みご飯風', 'Squid rice'), pair('詰めずに、刻んだイカと米を同じ味つけで炊く。', 'Skip the stuffing: cook chopped squid with rice in the same seasoning.')],
    ],
  },
  {
    id: 'yari-nitsuke',
    name: pair('ヤリイカの煮付け', 'Simmered spear squid'),
    time: 20,
    kind: pair('煮る', 'Simmer'),
    icon: '🍲',
    squid: ['yari', 'kensaki'],
    intro: pair('やわらかいヤリイカは、さっと煮るのがいちばん。春の子持ちは、ごちそうに。', 'Tender spear squid is best simmered briefly. In spring, egg-laden females make it a feast.'),
    ingredients: [
      [pair('ヤリイカ', 'Spear squid'), 4, pair('杯', '')],
      [pair('水', 'Water'), 100, 'ml'],
      [pair('醤油', 'Soy sauce'), 30, 'ml'],
      [pair('みりん', 'Mirin'), 30, 'ml'],
      [pair('酒', 'Sake'), 30, 'ml'],
      [pair('砂糖', 'Sugar'), 10, 'g'],
      [pair('生姜（薄切り）', 'Sliced ginger'), 10, 'g'],
    ],
    steps: [
      pair('足とワタ、軟骨を抜いて洗う。胴は筒のまま、足は目とクチバシを取って食べやすく切る。', 'Remove arms, innards and cartilage and rinse. Keep the mantle whole; trim eyes and beak from the arms and cut them up.'),
      pair('鍋に水・調味料・生姜を入れて煮立てる。', 'Bring the water, seasonings and ginger to a boil.'),
      pair('イカを入れ、煮汁をかけながら中火で4〜5分、中まで火を通す。', 'Add the squid and cook 4–5 minutes over medium heat, basting, until cooked through.'),
      pair('イカを取り出し、煮汁を少し煮詰めてから戻して絡める。', 'Lift out the squid, reduce the liquid slightly, then return the squid and coat.'),
    ],
    tip: pair('イカは長く煮ると硬くなります。「さっと煮る」か「30分以上じっくり煮てやわらかく戻す」かのどちらかに。', 'Squid toughens with moderate cooking. Either simmer it briefly, or go long (30+ minutes) until it softens again.'),
    variations: [
      [pair('子持ちヤリイカ', 'Egg-laden spear squid'), pair('春の子持ちは、卵を抜かずにそのまま煮る。卵の中までしっかり火を通す。', 'In spring, simmer females with their eggs inside, making sure the eggs are cooked through.')],
      [pair('大根と一緒に', 'With daikon'), pair('「イカと大根の生姜煮」の作り方で、じっくり煮る。', 'Follow the ginger-simmered squid & daikon recipe for a long, slow version.')],
      [pair('里芋と煮る', 'With taro'), pair('下ゆでした里芋を先に煮て、最後にイカを入れる。', 'Simmer parboiled taro first and add the squid at the end.')],
    ],
  },
  {
    id: 'yari-okizuke',
    name: pair('ヤリイカの沖漬け（冷凍して）', 'Soy-marinated spear squid (okizuke, frozen)'),
    time: 15,
    kind: pair('漬ける', 'Marinate'),
    icon: '🧊',
    raw: true,
    squid: ['yari', 'kensaki'],
    intro: pair('新鮮なイカを丸ごとタレに漬けて凍らせる、釣り人のごちそう。半解凍を輪切りで。', 'An angler’s treat: fresh squid marinated whole in soy and frozen. Slice it half-thawed.'),
    ingredients: [
      [pair('新鮮なヤリイカ', 'Very fresh spear squid'), 4, pair('杯', '')],
      [pair('醤油', 'Soy sauce'), 100, 'ml'],
      [pair('酒', 'Sake'), 50, 'ml'],
      [pair('みりん', 'Mirin'), 50, 'ml'],
    ],
    steps: [
      pair('小鍋で酒とみりんを煮立ててアルコールを飛ばし、醤油を加えて冷ます。冷蔵庫でよく冷やす。', 'Boil the sake and mirin to cook off the alcohol, add the soy sauce and chill thoroughly.'),
      pair('イカは洗って水分をふき、丸ごと（ワタごと）タレに入れて保存袋に移す。', 'Rinse and dry the squid and put them whole—innards and all—into a freezer bag with the marinade.'),
      pair('袋を平らにして、−20℃以下で24時間以上冷凍する。', 'Lay the bag flat and freeze at −20°C or below for at least 24 hours.'),
      pair('食べるときは半解凍で取り出し、輪切りにする。ワタも一緒に食べられる。', 'Take it out half-thawed and slice into rings; the liver is eaten too.'),
    ],
    tip: pair('タレに漬けても寄生虫は防げません。冷凍の条件を守ること。鮮度の落ちたイカでは作らないで。', 'The marinade does not kill parasites—the freezing does. Use only very fresh squid.'),
    variations: [
      [pair('沖漬け丼', 'Okizuke rice bowl'), pair('輪切りを温かいごはんにのせ、刻みのりを。', 'Lay slices over hot rice with shredded nori.')],
      [pair('大葉巻き', 'Wrapped in shiso'), pair('輪切りを大葉で巻いておつまみに。', 'Wrap slices in shiso leaves as a snack.')],
      [pair('焼いて食べる', 'Grilled'), pair('解凍して丸ごと焼くと、香ばしい別の味に（中までしっかり焼く）。', 'Thaw and grill whole for a smoky, savory version—cook it through.')],
    ],
  },
  {
    id: 'kou-sumi-pasta',
    name: pair('コウイカのイカ墨パスタ', 'Cuttlefish ink pasta'),
    time: 25,
    kind: pair('洋風', 'Pasta'),
    icon: '🍝',
    squid: ['kouika', 'mongo'],
    intro: pair('墨がたっぷりのコウイカだからできる、真っ黒なごちそう。', 'A jet-black feast made with the generous ink of a fresh cuttlefish.'),
    ingredients: [
      [pair('さばいたコウイカ（身・ゲソ）', 'Cleaned cuttlefish (body and arms)'), 200, 'g'],
      [pair('コウイカの墨袋', 'Cuttlefish ink sac'), 1, pair('個', '')],
      [pair('乾燥パスタ', 'Dried pasta'), 180, 'g'],
      [pair('にんにく', 'Garlic'), 8, 'g'],
      [pair('オリーブ油', 'Olive oil'), 20, 'ml'],
      [pair('白ワイン', 'White wine'), 30, 'ml'],
      [pair('カットトマト缶', 'Canned chopped tomatoes'), 100, 'g'],
      [pair('塩', 'Salt'), 2, 'g'],
    ],
    steps: [
      pair('さばくときに墨袋を破らずに外し、小皿に墨をしぼり出して白ワインで溶く。', 'Remove the ink sac intact, squeeze the ink into a dish and loosen it with the wine.'),
      pair('イカは食べやすく切る。パスタは袋の表示どおりにゆで始める。', 'Cut the cuttlefish into bite-size pieces. Start cooking the pasta according to the packet.'),
      pair('フライパンにオリーブ油と刻んだにんにくを入れて弱火で温め、香りが出たらイカを炒めて中まで火を通す。', 'Warm chopped garlic in olive oil over low heat, then sauté the cuttlefish until cooked through.'),
      pair('トマトと墨ワインを加えて2〜3分煮る。塩で味を調える。', 'Add the tomatoes and inky wine and simmer 2–3 minutes. Season with salt.'),
      pair('パスタを加えて絡める。固ければゆで汁を少し足す。', 'Toss in the pasta, loosening with a little cooking water if needed.'),
    ],
    tip: pair('墨は服や木のまな板につくと落ちにくい。エプロンをして、まな板にラップを敷いて。', 'Ink stains clothes and wooden boards. Wear an apron and cover the board with plastic wrap.'),
    variations: [
      [pair('イカ墨リゾット', 'Ink risotto'), pair('パスタの代わりにごはんと水を入れて煮詰め、粉チーズを。', 'Use rice and water instead of pasta, simmer down and finish with grated cheese.')],
      [pair('墨を使わずペペロンチーノ', 'Without ink: aglio e olio'), pair('トマトと墨を入れず、にんにくと唐辛子で。', 'Leave out the tomato and ink; just garlic and chili.')],
    ],
  },
  {
    id: 'kou-fry',
    name: pair('コウイカのフライ', 'Breaded cuttlefish'),
    time: 25,
    kind: pair('揚げる', 'Deep-fry'),
    icon: '🍤',
    squid: ['kouika', 'mongo', 'aori'],
    intro: pair('厚い身がサクッと、中はやわらか。切り目がやわらかさのカギ。', 'Crisp outside, tender inside. Scoring the thick flesh is the secret.'),
    ingredients: [
      [pair('さばいたコウイカの身', 'Cleaned cuttlefish body'), 250, 'g'],
      [pair('塩', 'Salt'), 1, 'g'],
      [pair('こしょう', 'Pepper'), 0.5, 'g'],
      [pair('小麦粉', 'Flour'), 20, 'g'],
      [pair('卵', 'Egg'), 1, pair('個', '')],
      [pair('パン粉', 'Panko breadcrumbs'), 40, 'g'],
      [pair('揚げ油', 'Oil for frying'), 500, 'ml'],
    ],
    steps: [
      pair('身の両面に浅く格子の切り目を入れ、1cm幅の短冊に切る。水分をふいて塩こしょう。', 'Score both sides in a shallow crosshatch, cut into 1cm strips, pat dry and season.'),
      pair('小麦粉、溶き卵、パン粉の順に衣をつける。', 'Coat in flour, beaten egg and panko.'),
      pair('170℃の油で2〜3分、きつね色になり中まで火が通るまで揚げる。', 'Fry at 170°C for 2–3 minutes until golden and cooked through.'),
    ],
    tip: pair('コウイカの身は厚く締まっています。格子の切り目で噛み切りやすく、反り返りも防げます。', 'Cuttlefish is thick and dense; crosshatching makes it easy to bite and keeps it flat.'),
    variations: [
      [pair('タルタルソース', 'Tartar sauce'), pair('刻みゆで卵・玉ねぎ・マヨネーズで。', 'Chopped boiled egg, onion and mayonnaise.')],
      [pair('ゲソフライ', 'Fried arms'), pair('足も同じ衣で揚げる。', 'Bread and fry the arms the same way.')],
      [pair('卵とじ丼', 'Egg-topped rice bowl'), pair('だしで玉ねぎを煮て、フライをのせて卵でとじる。', 'Simmer onion in dashi, add the fried cuttlefish and set with egg over rice.')],
    ],
  },
  {
    id: 'mongo-karaage',
    name: pair('モンゴウイカの唐揚げ', 'Japanese-style fried cuttlefish (karaage)'),
    time: 25,
    kind: pair('揚げる', 'Deep-fry'),
    icon: '🍗',
    squid: ['mongo', 'kouika', 'aori'],
    intro: pair('大きくて身が厚いモンゴウイカは、唐揚げにぴったり。お弁当にも。', 'Big, thick kisslip cuttlefish is perfect for karaage—great in lunch boxes too.'),
    ingredients: [
      [pair('さばいたモンゴウイカの身', 'Cleaned cuttlefish body'), 300, 'g'],
      [pair('醤油', 'Soy sauce'), 15, 'ml'],
      [pair('酒', 'Sake'), 15, 'ml'],
      [pair('おろし生姜', 'Grated ginger'), 5, 'g'],
      [pair('おろしにんにく', 'Grated garlic'), 3, 'g'],
      [pair('片栗粉', 'Potato starch'), 30, 'g'],
      [pair('揚げ油', 'Oil for frying'), 500, 'ml'],
    ],
    steps: [
      pair('薄皮をむき、浅い格子の切り目を入れて、厚さ1cmほどの一口大に切る。', 'Skin the body, score it lightly in a crosshatch and cut into bite-size pieces about 1cm thick.'),
      pair('醤油・酒・生姜・にんにくに10分漬ける。', 'Marinate 10 minutes in soy, sake, ginger and garlic.'),
      pair('汁気をきり、片栗粉をまぶす。', 'Drain and dust with potato starch.'),
      pair('170℃の油で2〜3分、中まで火が通るまで揚げる。油はねに気をつけて。', 'Fry at 170°C for 2–3 minutes until cooked through. Watch for spattering.'),
    ],
    tip: pair('大きな身は厚さをそろえて切ると、均一に火が通ります。水分をよくふくと油がはねにくい。', 'Cut the large body to an even thickness so it cooks evenly; drying it well reduces spatter.'),
    variations: [
      [pair('塩唐揚げ', 'Salt karaage'), pair('醤油の代わりに塩と酒で下味を。レモンを添えて。', 'Season with salt and sake instead of soy; serve with lemon.')],
      [pair('竜田揚げ', 'Tatsuta-age'), pair('片栗粉を多めにまぶして、白っぽくカリッと。', 'Use more starch for a pale, extra-crisp crust.')],
      [pair('甘酢あん', 'Sweet-and-sour'), pair('揚げたイカに、酢・砂糖・ケチャップのあんを絡める。', 'Toss the fried pieces in a vinegar, sugar and ketchup glaze.')],
    ],
  },
  {
    id: 'mongo-stirfry',
    name: pair('モンゴウイカとセロリの塩炒め', 'Cuttlefish & celery stir-fry'),
    time: 15,
    kind: pair('炒める', 'Stir-fry'),
    icon: '🥢',
    squid: ['mongo', 'kouika', 'aori'],
    intro: pair('歯ごたえのある身とシャキシャキのセロリ。中華の塩味で、さっと。', 'Firm cuttlefish and crunchy celery in a quick, light Chinese-style stir-fry.'),
    ingredients: [
      [pair('さばいたモンゴウイカの身', 'Cleaned cuttlefish body'), 250, 'g'],
      [pair('セロリ', 'Celery'), 100, 'g'],
      [pair('長ねぎ', 'Japanese leek'), 30, 'g'],
      [pair('生姜', 'Fresh ginger'), 5, 'g'],
      [pair('ごま油', 'Sesame oil'), 15, 'ml'],
      [pair('酒', 'Sake'), 15, 'ml'],
      [pair('鶏がらスープの素', 'Chicken stock powder'), 3, 'g'],
      [pair('塩', 'Salt'), 1, 'g'],
      [pair('片栗粉（同量の水で溶く）', 'Potato starch (mixed with equal water)'), 3, 'g'],
    ],
    steps: [
      pair('イカは格子の切り目を入れて一口大に。セロリは斜め薄切り、ねぎと生姜はみじん切り。', 'Crosshatch the cuttlefish and cut into bite-size pieces. Slice celery on the diagonal; mince leek and ginger.'),
      pair('ごま油でねぎと生姜を炒め、香りが出たらイカを入れて中まで火を通す。', 'Stir-fry leek and ginger in sesame oil until fragrant, then add the cuttlefish and cook through.'),
      pair('セロリ・酒・スープの素・塩を加えて手早く炒め合わせる。', 'Add celery, sake, stock powder and salt and toss quickly.'),
      pair('水溶き片栗粉を回し入れ、とろみがついたら火を止める。', 'Stir in the starch slurry and turn off the heat once glossy.'),
    ],
    tip: pair('格子の切り目を入れると、火が通ると花のように開いて味が絡みます。', 'Crosshatched pieces curl open like flowers as they cook and hold the sauce.'),
    variations: [
      [pair('オイスターソース炒め', 'Oyster sauce'), pair('塩の代わりにオイスターソース大さじ1。', 'Use a tablespoon of oyster sauce instead of salt.')],
      [pair('イカチリ', 'Chili squid'), pair('ケチャップと豆板醤で、エビチリ風に。', 'Ketchup and chili bean paste, like chili shrimp.')],
      [pair('青菜炒め', 'With greens'), pair('セロリの代わりにチンゲン菜や小松菜で。', 'Swap the celery for bok choy or komatsuna.')],
    ],
  },
];
